# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=50)),
                ('siteusername', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('usage', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('vis', models.PositiveSmallIntegerField()),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('displayname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('vis', models.PositiveSmallIntegerField()),
                ('profileImg', models.CharField(max_length=200)),
                ('bgImg', models.CharField(max_length=200)),
                ('useBg', models.BooleanField(max_length=50)),
            ],
        ),
    ]
