# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160504_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='fromuser',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='touser',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fromuser',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='touser',
            field=models.PositiveIntegerField(),
        ),
    ]
