# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(default='logo/myeh.jpg', upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bgImg',
            field=models.ImageField(default='bg/myeh.jpg', upload_to='bg/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(default='pic/myeh.jpg', upload_to='pic/'),
        ),
    ]
